export { default as Calendar } from './Calendar';
export { default as Calculator } from './Calculator';
export { default as Alarm } from './Alarm';
export { default as Contact } from './Contact';
export { default as Camera } from './Camera';
export { default as Gallery } from './Gallery';
export { default as Note } from './Note';
export { default as Phone } from './Phone';
export { default as Chatgpt } from './Chatgpt';